# Notebook 6 – Data Inspection
**Filename:** `06_Data_Inspection.ipynb`

Data inspection means checking the size, structure, data types, missing values, and value distributions before analysis. It helps catch problems early.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["Asha", "Ravi", "Mina", "John", "Asha", "Ravi"],
    "Department": ["Sales", "IT", "IT", "HR", "Sales", "HR"],
    "Salary": [30000, 45000, 42000, 28000, 32000, 31000],
    "Experience": [1, 3, 2, 1, 2, 1]
})
display(df)

  Employee Department  Salary  Experience
0     Asha      Sales   30000           1
1     Ravi         IT   45000           3
2     Mina         IT   42000           2
3     John         HR   28000           1
4     Asha      Sales   32000           2
5     Ravi         HR   31000           1

## `head()`
**Definition:** Shows the first rows (default five).

**Real-world meaning:** Check the first few sales records after importing a file.

In [2]:
display(df.head())

  Employee Department  Salary  Experience
0     Asha      Sales   30000           1
1     Ravi         IT   45000           3
2     Mina         IT   42000           2
3     John         HR   28000           1
4     Asha      Sales   32000           2

## `tail()`
**Definition:** Shows the last rows (default five).

**Real-world meaning:** Check whether the file ends with expected records.

In [3]:
display(df.tail(2))

  Employee Department  Salary  Experience
4     Asha      Sales   32000           2
5     Ravi         HR   31000           1

## `sample()`
**Definition:** Returns random rows.

**Real-world meaning:** Spot-check records without always viewing the same rows.

In [4]:
display(df.sample(2, random_state=1))

  Employee Department  Salary  Experience
2     Mina         IT   42000           2
1     Ravi         IT   45000           3

## `info()`
**Definition:** Shows row count, column names, non-null counts, and dtypes.

**Real-world meaning:** Find columns with missing values and unexpected types.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Employee    6 non-null      str
 1   Department  6 non-null      str
 2   Salary      6 non-null      int64
 3   Experience  6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 366.0 bytes

## `describe()`
**Definition:** Summarizes numeric columns by count, mean, standard deviation, min, quartiles, and max.

**Real-world meaning:** Review sales values and detect unusually large values.

In [ ]:
display(df.describe())

## `shape`
**Definition:** Returns (number_of_rows, number_of_columns).

**Real-world meaning:** Confirm the size of a dataset.

In [ ]:
display(df.shape)

## `columns`
**Definition:** Returns column labels.

**Real-world meaning:** Check imported field names.

In [ ]:
display(df.columns)

## `dtypes`
**Definition:** Returns each column's data type.

**Real-world meaning:** Find numeric values mistakenly imported as text.

In [ ]:
display(df.dtypes)

## `memory_usage()`
**Definition:** Estimates memory used by each column.

**Real-world meaning:** Understand memory needs for large datasets.

In [ ]:
display(df.memory_usage(deep=True))

## `nunique()`
**Definition:** Counts distinct values in each column by default.

**Real-world meaning:** Count unique customers or categories.

In [ ]:
display(df.nunique())

## `value_counts()`
**Definition:** Counts occurrences of each value in a Series.

**Real-world meaning:** Find the most common product category.

In [ ]:
display(df['Department'].value_counts())

## Recommended inspection workflow
1. `df.shape` – check dimensions.
2. `df.head()` – preview rows.
3. `df.info()` and `df.isna().sum()` – inspect types and missing values.
4. `df.describe()` – understand numeric ranges.
5. `value_counts()` and `nunique()` – inspect categories.

**AI/ML use case:** Before training a model, inspect data types, missing values, category frequencies, and numeric ranges. This represents data inspection because model quality depends on understanding the data before fitting the model.

## Practice
Inspect a DataFrame of your own and write down its row count, column count, data types, missing-value counts, and most common category.