# Notebook 8 – Data Manipulation
**Filename:** `08_Data_Manipulation.ipynb`

Data manipulation changes column names, rows, values, or derived fields so a dataset is easier to analyze. Many Pandas methods return a new DataFrame unless you assign the result back.

In [2]:
import pandas as pd

df = pd.DataFrame({
    "employee_name": ["Asha", "Ravi", "Mina", "Ravi"],
    "department": ["Sales", "IT", "IT", "IT"],
    "salary": [30000, 55000, 48000, 55000]
})
display(df)

  employee_name department  salary
0          Asha      Sales   30000
1          Ravi         IT   55000
2          Mina         IT   48000
3          Ravi         IT   55000

## 1. Rename columns
`rename()` maps existing column labels to new labels. Assign the result or use `inplace=True` (assignment is often clearer).

In [3]:
df = df.rename(columns={"employee_name": "Name", "department": "Department", "salary": "Salary"})
display(df)

   Name Department  Salary
0  Asha      Sales   30000
1  Ravi         IT   55000
2  Mina         IT   48000
3  Ravi         IT   55000

## 2. Drop rows
`drop()` removes index labels. Use `errors='ignore'` only when it is acceptable for a missing label not to raise an error.

In [ ]:
without_first = df.drop(index=0)
display(without_first)

## 3. Drop columns
Use `drop(columns=[...])` to remove unwanted fields.

In [ ]:
without_department = df.drop(columns=["Department"])
display(without_department)

## 4. Insert columns
`insert()` adds a column at a specified position and modifies the DataFrame.

In [ ]:
df.insert(2, "AnnualBonus", [1000, 3000, 2500, 3000])
display(df)

## 5. `assign()`
Creates a DataFrame with new or updated columns and returns it, leaving the original unchanged unless you reassign it.

In [ ]:
df2 = df.assign(MonthlySalary=df["Salary"] / 12)
display(df2)

## 6. `apply()`
Applies a function along a Series or DataFrame axis. It is flexible, though vectorized operations are often faster for simple calculations.

In [ ]:
df["SalaryBand"] = df["Salary"].apply(lambda salary: "High" if salary >= 50000 else "Standard")
display(df)

## 7. `map()`
For a Series, maps each value through a dictionary or function. Unmapped dictionary values become missing (`NaN`).

In [ ]:
department_names = {"IT": "Technology", "Sales": "Sales Team"}
df["DepartmentLabel"] = df["Department"].map(department_names)
display(df)

## 8. `replace()`
Replaces specific values with other values. Useful for standardizing inconsistent labels.

In [ ]:
labels = pd.Series(["NY", "N.Y.", "CA", "NY"])
standardized = labels.replace({"N.Y.": "NY"})
display(standardized)

## 9. Duplicate handling
`duplicated()` identifies duplicate rows; `drop_duplicates()` removes them. Decide which columns define a duplicate before removing records.

In [ ]:
print("Duplicate full rows:")
display(df[df.duplicated()])
unique_employees = df.drop_duplicates(subset=["Name", "Department"], keep="first")
display(unique_employees)

## Business and AI/ML use cases
- **Business:** Rename inconsistent columns, remove duplicate customer records, and calculate a bonus column.
- **AI/ML:** Standardize category labels and create a derived feature such as salary band.
- **Why this represents manipulation:** Each step changes the dataset's structure or values to make records consistent and useful.

## Practice
1. Rename `SalaryBand` to `PayCategory`.
2. Create a column with salary plus annual bonus.
3. Replace a misspelled category.
4. Find and remove duplicate records, explaining your chosen duplicate criteria.